function f = CalculateClusterAccuracy()

sArr_ResultFiles = [ ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withoutPlaceName_10_5_10.csv   '; ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withoutPlaceName_10_5_20.csv   '; ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withoutPlaceName_10_5_30.csv   '; ...

%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withPlaceName_10_5_20.csv      '; ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withPlaceName_10_5_30.csv      '; ...

%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withoutPlaceName_9_3_20.csv                      '; ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withPlaceName_9_3_20.csv                     '; ...

%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withoutPlaceName_8_4_20.csv                      '; ...
%     'E:\UIUC\Run\ClusteringResult\ClusteringResultSimple_withPlaceName_8_4_20.csv                     '; ...

%      'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withoutPlaceName_8_4_50.csv     '; ...
%     'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withPlaceName_8_4_50.csv        '; ...
%     'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withoutPlaceName_9_3_50.csv     '; ...
%     'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withPlaceName_9_3_50.csv        '; ...

%      'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withoutPlaceName_10_5_20.csv    '; ...
%       'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withoutPlaceName_10_5_50.csv    '; ...
%      'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withoutPlaceName_10_5_60.csv    '; ...

      'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withPlaceName_10_5_20.csv       '; ...
      'E:\UIUC\Run\ClusteringResult\Result\ClusteringResultSimple_withPlaceName_10_5_50.csv       '; ...
     
];

cellResultFiles = cellstr(sArr_ResultFiles);

nTotalEvalCnt = 0;
nTotalCorrectCnt = 0;
fTotalAccuracy = 0.0;

for i=1:length(cellResultFiles)
    mResult = CalculateOneResult(cellResultFiles{i});
    
    nTotalEvalCnt = nTotalEvalCnt + mResult(1,1);
    nTotalCorrectCnt = nTotalCorrectCnt + mResult(1,2);
    fTotalAccuracy = fTotalAccuracy + mResult(1,3);
end

fAverageAccuracy = fTotalAccuracy/nTotalEvalCnt;

fprintf('Total:  %d    ;   Correct Portion:  %f;    Average Accuracy:  %f\n', nTotalEvalCnt, nTotalCorrectCnt/nTotalEvalCnt,  fAverageAccuracy);

return;
